Load the packages and create the dataframe from the CSV in the Resouces folder

In [1]:
import pandas as pd
ico_inventories = "../Resources/inventories.csv"
ico_price_to_grower = "../Resources/prices-paid-to-growers.csv"
ico_inventories_df = pd.read_csv(ico_inventories)
ico_price_to_grower_df = pd.read_csv(ico_price_to_grower)

In [2]:
ico_inventories_df

,inventories,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Austria,333.0,333.0,367.0,333.0,283.0,274.0,246.0,231.0,210.0,...,138.0,141.0,111.0,97.0,92.0,96.0,96.0,90.0,80.0,80.0
1,Cyprus,10.0,12.0,10.0,8.0,13.0,13.0,12.0,6.0,9.0,...,5.0,5.0,6.0,4.0,7.0,12.0,6.0,2.0,3.0,5.0
2,Denmark,89.0,89.0,89.0,89.0,89.0,89.0,89.0,89.0,89.0,...,89.0,89.0,89.0,89.0,89.0,89.0,89.0,89.0,89.0,89.0
3,Finland,176.0,223.0,213.0,188.0,282.0,220.0,140.0,181.0,162.0,...,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0
4,France,573.0,562.0,537.0,389.0,481.0,301.0,266.0,317.0,350.0,...,483.0,427.0,414.0,446.0,438.0,499.0,507.0,572.0,475.0,464.0
5,Germany,4000.0,1600.0,2500.0,2000.0,3900.0,2300.0,1600.0,1900.0,1600.0,...,2911.0,2680.0,2462.0,2859.0,2636.0,3120.0,3519.0,3991.0,3601.0,3518.0
6,Ireland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,4.0,6.0,7.0,6.0,6.0,4.0,4.0,4.0,3.0
7,Italy,215.0,189.0,187.0,228.0,222.0,217.0,223.0,227.0,234.0,...,317.0,326.0,329.0,346.0,352.0,371.0,370.0,403.0,396.0,396.0
8,Netherlands,1752.0,1752.0,1048.0,707.0,707.0,707.0,707.0,707.0,707.0,...,707.0,707.0,707.0,707.0,707.0,707.0,707.0,707.0,707.0,707.0
9,Portugal,68.0,143.0,121.0,220.0,159.0,86.0,115.0,131.0,101.0,...,100.0,101.0,90.0,110.0,120.0,100.0,129.0,129.0,129.0,129.0
10,Spain,200.0,250.0,333.0,250.0,267.0,284.0,303.0,323.0,344.0,...,570.0,570.0,570.0,570.0,837.0,640.0,637.0,734.0,723.0,715.0
11,Sweden,87.0,87.0,87.0,87.0,87.0,87.0,87.0,87.0,87.0,...,87.0,87.0,87.0,87.0,87.0,87.0,87.0,87.0,87.0,87.0
12,United Kingdom,189.0,168.0,170.0,204.0,213.0,187.0,132.0,110.0,128.0,...,72.0,47.0,41.0,41.0,39.0,40.0,43.0,26.0,20.0,29.0
13,Japan,1500.0,1167.0,1333.0,1250.0,1467.0,833.0,983.0,917.0,883.0,...,1683.0,1755.0,2204.0,2027.0,2881.0,2934.0,3185.0,3229.0,3021.0,2603.0
14,Norway,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,...,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0,124.0
15,Switzerland,321.0,351.0,302.0,327.0,286.0,193.0,140.0,118.0,165.0,...,161.0,154.0,203.0,209.0,206.0,206.0,217.0,219.0,368.0,338.0
16,USA,5982.0,6150.0,9422.0,7814.0,4087.0,1990.0,1327.0,1428.0,1408.0,...,4570.0,3974.0,4295.0,4736.0,5087.0,5525.0,5836.0,6256.0,6632.0,6133.0

In [3]:
ico_price_to_grower_df

,prices_paid_to_growers,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Colombia,1.534724,1.481790,1.204656,1.106477,1.898327,2.199185,2.065245,2.939673,2.253433,...,3.067442,3.985616,5.290868,3.679737,2.514539,3.525662,2.635854,2.727530,2.776185,2.505914
1,Dominican Republic,1.458168,1.382845,1.027841,1.172704,2.478234,2.412000,1.935342,3.673587,2.102616,...,2.340731,3.071276,4.217812,3.262839,3.112084,4.052172,3.775011,3.911395,3.826974,3.391053
2,El Salvador,1.116194,0.983322,0.682322,0.780397,2.191177,2.218826,1.656073,2.762552,1.877384,...,1.748205,2.425620,4.122256,2.651658,2.103276,2.582929,1.930439,1.976442,1.934159,1.645300
3,Guatemala,1.204956,1.270086,0.888099,0.914552,1.662711,2.192936,1.849170,2.146819,2.261521,...,2.420375,3.195830,4.689066,3.664007,2.804848,3.373810,3.073230,2.990444,2.960790,2.697022
4,Honduras,1.111470,1.238947,0.886057,0.828746,1.800576,2.263781,1.493616,2.580166,2.058671,...,1.848015,2.762887,4.415430,3.115841,2.247159,2.625614,2.449565,2.056691,2.003671,1.855291
5,India,1.473558,1.358371,1.191159,1.278669,1.730810,1.870104,1.728881,2.873698,2.195885,...,3.021792,3.335051,5.043230,3.575634,2.584011,3.877464,3.467918,2.918461,2.996744,2.430896
6,Uganda,0.337598,0.654322,0.441397,0.552298,1.666651,1.506821,1.169927,1.772936,1.738302,...,1.336532,1.925611,3.245623,2.068040,1.545905,2.289245,1.794042,1.569419,1.699698,1.506691
7,Brazil,1.199223,0.971150,0.997768,1.167263,2.529110,2.550172,2.126834,3.209923,2.323380,...,2.225150,2.957956,4.950552,3.361764,2.254700,2.973442,2.306547,2.380366,2.438757,2.003980
8,Ethiopia,1.348565,1.505322,1.351128,1.362442,2.418234,2.539011,1.495287,2.010060,2.027901,...,1.701150,1.886530,3.211088,2.269088,1.618110,1.837430,1.678360,1.927316,1.799278,1.560234
9,Brazil,0.769285,0.606947,0.609155,0.784638,1.885786,2.152316,1.540377,1.718671,1.716276,...,1.620826,1.638355,2.324366,2.304737,1.882698,1.791693,1.623110,2.048073,2.168022,1.488327
10,India,0.978921,0.897289,0.877945,0.975912,1.246437,1.468722,1.251075,1.684362,1.669311,...,1.614300,1.720954,2.419479,2.310181,2.094377,2.309801,1.941468,1.825872,2.096424,1.732519
11,Togo,0.645267,0.632307,0.658494,0.499857,0.573784,1.355618,1.381453,0.990868,1.102214,...,0.986980,0.934989,1.636711,1.512095,1.469380,1.321912,1.314625,1.451042,1.517221,1.565731
12,Uganda,0.166486,0.261430,0.197653,0.259737,0.919709,1.319927,0.826408,0.920245,0.883455,...,1.082366,1.227616,1.623302,1.585093,1.494598,1.549219,1.329269,1.311532,1.411808,1.263373

In [4]:
ico_inventories_df=ico_inventories_df.rename(columns={"inventories": "Country"})
ico_price_to_grower_df=ico_price_to_grower_df.rename(columns={"prices_paid_to_growers": "Country"})
ico_inventories_df=ico_inventories_df.dropna()
ico_price_to_grower_df=ico_price_to_grower_df.dropna()
ico_inventories_ten=ico_inventories_df[["Country", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"]]
ico_price_to_grower_ten=ico_price_to_grower_df[["Country", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"]]

ico_price_to_grower_ten = ico_price_to_grower_ten.transpose()
ico_price_to_grower_ten = ico_price_to_grower_ten.reset_index(drop=False)
new_header = ico_price_to_grower_ten.iloc[0]
ico_price_to_grower_ten = ico_price_to_grower_ten[1:]
ico_price_to_grower_ten.columns = new_header 
ico_price_to_grower_ten=ico_price_to_grower_ten.rename(columns={"Country": "Year"})
ico_price_to_grower_ten=ico_price_to_grower_ten.loc[:, (ico_price_to_grower_ten != 0).any(axis=0)]

ico_inventories_ten = ico_inventories_ten.transpose()
ico_inventories_ten = ico_inventories_ten.reset_index(drop=False)
new_header = ico_inventories_ten.iloc[0]
ico_inventories_ten = ico_inventories_ten[1:]
ico_inventories_ten.columns = new_header 
ico_inventories_ten=ico_inventories_ten.rename(columns={"Country": "Year"})
ico_inventories_ten=ico_inventories_ten.loc[:, (ico_inventories_ten != 0).any(axis=0)]

In [5]:
ico_inventories_ten

,Year,Austria,Cyprus,Denmark,Finland,France,Germany,Italy,Netherlands,Portugal,Spain,Sweden,United Kingdom,Japan,Norway,Switzerland,USA
1,2009,138,5,89,83,483,2911,317,707,100,570,87,72,1683,124,161,4570
2,2010,141,5,89,83,427,2680,326,707,101,570,87,47,1755,124,154,3974
3,2011,111,6,89,83,414,2462,329,707,90,570,87,41,2204,124,203,4295
4,2012,97,4,89,83,446,2859,346,707,110,570,87,41,2027,124,209,4736
5,2013,92,7,89,83,438,2636,352,707,120,837,87,39,2881,124,206,5087
6,2014,96,12,89,83,499,3120,371,707,100,640,87,40,2934,124,206,5525
7,2015,96,6,89,83,507,3519,370,707,129,637,87,43,3185,124,217,5836
8,2016,90,2,89,83,572,3991,403,707,129,734,87,26,3229,124,219,6256
9,2017,80,3,89,83,475,3601,396,707,129,723,87,20,3021,124,368,6632
10,2018,80,5,89,83,464,3518,396,707,129,715,87,29,2603,124,338,6133

In [7]:
ico_price_to_grower_ten

,Year,Colombia,Dominican Republic,El Salvador,Guatemala,Honduras,India,Uganda,Brazil,Ethiopia,Brazil,India,Togo,Uganda
1,2009,3.06744,2.34073,1.74821,2.42038,1.84802,3.02179,1.33653,2.22515,1.70115,1.62083,1.6143,0.98698,1.08237
2,2010,3.98562,3.07128,2.42562,3.19583,2.76289,3.33505,1.92561,2.95796,1.88653,1.63836,1.72095,0.934989,1.22762
3,2011,5.29087,4.21781,4.12226,4.68907,4.41543,5.04323,3.24562,4.95055,3.21109,2.32437,2.41948,1.63671,1.6233
4,2012,3.67974,3.26284,2.65166,3.66401,3.11584,3.57563,2.06804,3.36176,2.26909,2.30474,2.31018,1.51209,1.58509
5,2013,2.51454,3.11208,2.10328,2.80485,2.24716,2.58401,1.54591,2.2547,1.61811,1.8827,2.09438,1.46938,1.4946
6,2014,3.52566,4.05217,2.58293,3.37381,2.62561,3.87746,2.28925,2.97344,1.83743,1.79169,2.3098,1.32191,1.54922
7,2015,2.63585,3.77501,1.93044,3.07323,2.44957,3.46792,1.79404,2.30655,1.67836,1.62311,1.94147,1.31462,1.32927
8,2016,2.72753,3.9114,1.97644,2.99044,2.05669,2.91846,1.56942,2.38037,1.92732,2.04807,1.82587,1.45104,1.31153
9,2017,2.77619,3.82697,1.93416,2.96079,2.00367,2.99674,1.6997,2.43876,1.79928,2.16802,2.09642,1.51722,1.41181
10,2018,2.50591,3.39105,1.6453,2.69702,1.85529,2.4309,1.50669,2.00398,1.56023,1.48833,1.73252,1.56573,1.26337